abrigo_animais/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animal.urls', namespace='animais')),  
    path('adocao/', include('adocao.urls', namespace='adocao')),    
    path('voluntarios/', include('voluntarios.urls', namespace='voluntarios')),      
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adocao/urls.py
from django.urls import path
from .views import solicitar_adocao

app_name = 'adocao'
urlpatterns = [
    path('', solicitar_adocao, name='solicitar_adocao'),
    
]

animal/urls.py
from django.urls import path
from animal.views import listar_animais, ver_animal, pagina_inicial

app_name = 'animais'
urlpatterns = [
    path('', pagina_inicial, name='pagina_inicial'),
    path('listar_animais/', listar_animais, name='listar_animais'),
    path('<int:id_animal>/', ver_animal, name='ver_animal')
]

voluntarios/urls.py
from django.urls import path
from .views import formulario_voluntario

app_name = 'voluntarios'
urlpatterns = [
    path('', formulario_voluntario, name='formulario_voluntario'),
]

adocao/models.py
from django.db import models
from django.contrib.auth.models import User

class SolicitacaoAdocao(models.Model):

    STATUS_CHOICES = (
        ('Pendente', 'Pendente'),
        ('Aprovada', 'Aprovada'),
        ('Recusada', 'Recusada'),
    )

    nome = models.CharField(max_length=50)
    email = models.EmailField(max_length=75)
    endereco = models.CharField(max_length=100)
    outros_animais = models.IntegerField(default=0)
    animal = models.ForeignKey('animal.Animal', on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pendente')
    aprovado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Solicitação de Adoção de {self.animal.nome} por {self.nome} realizada com sucesso, aguardando aprovação."
    
    class Meta:
        verbose_name = 'Solicitação de adoção'
        verbose_name_plural = 'Solicitações de adoção'
        ordering = ['-data']

animal/models.py
from django.db import models

# Create your models here.
class HistoricoSaude(models.Model):
    choices_castracao = (('C', 'Castrado'),
                        ('N', 'Não castrado'))
    castrado = models.CharField(max_length=1, choices=choices_castracao, default='N')
    vacinas = models.CharField(max_length=200)
    idas_vet = models.TextField()

    class Meta:
        verbose_name = 'Histórico de saúde'
        verbose_name_plural = 'Histórico de saúde'
    
class Animal(models.Model):
    choices_sexo = (('F', 'Fêmea'),
                        ('M', 'Macho'))
    nome = models.CharField(max_length=100)
    especie = models.CharField(max_length=50)
    idade = models.IntegerField()
    raca = models.CharField(max_length=100)
    sexo = models.CharField(max_length=1, choices=choices_sexo)
    imagem = models.ImageField(upload_to='images/', null=True, blank=True)
    data_cadastro = models.DateTimeField(auto_now_add=True)
    historico_saude = models.ForeignKey(HistoricoSaude, on_delete=models.CASCADE)
    adotado = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Animal'
        verbose_name_plural = 'Animais'
        ordering = ['nome']

voluntarios/models.py
from django.db import models

class FormularioVoluntario(models.Model):
    opcoes_disponibilidade = [
        ('manha', 'Manhã'),
        ('tarde', 'Tarde'),
        ('noite', 'Noite')
    ]

    opcoes_experiencia = [
        ('sim', 'Sim'),
        ('não', 'Não'),
    ]

    nome = models.CharField(max_length=50)
    email = models.EmailField(max_length=75)
    endereco = models.CharField(max_length=100)
    motivo = models.TextField()
    disponibilidade = models.CharField(max_length=5, choices=opcoes_disponibilidade)
    experiencia =  models.CharField(max_length=3, choices=opcoes_experiencia)
    data = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Solicitação de voluntariado'
        verbose_name_plural = 'Solicitações de voluntariado'
        ordering = ['-data']

adocao/forms.py
from django import forms
from .models import SolicitacaoAdocao

class SolicitacaoAdocaoForm(forms.ModelForm):
    class Meta:
        model = SolicitacaoAdocao
        fields = ['nome', 'email', 'endereco', 'outros_animais', 'animal']
        widgets = {'status': forms.TextInput(attrs={'disabled': 'disabled'})}

voluntarios/forms.py
from django import forms
from .models import FormularioVoluntario

class FormularioVoluntarioForm(forms.ModelForm):
    class Meta:
        model = FormularioVoluntario
        fields = ['nome', 'email', 'endereco', 'motivo', 'disponibilidade', 'experiencia']

adocao/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms_adocao import SolicitacaoAdocaoForm  # Importe do novo arquivo forms_adocao.py
from animal.models import Animal
import os
from django.http import JsonResponse
from django.conf import settings

def solicitar_adocao(request):
    animais_disponiveis = Animal.objects.filter(adotado=False)
    if request.method == 'POST':
        form = SolicitacaoAdocaoForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'solicitar_adocao.html', {'alerta_sucesso': True})
    else:
        form = SolicitacaoAdocaoForm()

    contexto = {
        'form': form,
        'animais_disponiveis': animais_disponiveis,
    }
    return render(request, 'solicitar_adocao.html', contexto)

animal/views.py
from django.shortcuts import render
from animal.models import Animal

def pagina_inicial(request):    
    if 'especie' in request.GET:
        especie = request.GET.get('especie', '')
        animais = Animal.objects.filter(especie__icontains=especie)
        contexto = {
            'animais': animais,
        }
        return render(request, 'lista_animais.html', contexto)
    
    return render(request, 'home.html')

def listar_animais(request):
    especies = request.GET.get('especie') 
    animais = Animal.objects.filter(adotado=False)
    
    if especies:
        animais = animais.filter(especie=especies)

    contexto = {
        'animais': animais,
    }
    return render(request, 'lista_animais.html', contexto)

def ver_animal(request, id_animal):
    animal = Animal.objects.get(id=id_animal)
    return render(request, 'ver_animal.html', {'animal': animal})

voluntarios/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import FormularioVoluntarioForm
from .models import FormularioVoluntario

def formulario_voluntario(request):
    opcoes_disponibilidade = FormularioVoluntario.opcoes_disponibilidade
    opcoes_experiencia = FormularioVoluntario.opcoes_experiencia

    if request.method == 'POST':
        form = FormularioVoluntarioForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'cadastro.html', {'alerta_sucesso': True})
    else:
        form = FormularioVoluntarioForm()
    contexto = {
        'form': form,
        'opcoes_disponibilidade': opcoes_disponibilidade,
        'opcoes_experiencia': opcoes_experiencia
    }
    return render(request, 'cadastro.html', contexto)

adocao/templates/solicitar_adocao.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Solicitação de adoção</title>
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/1312/1312640.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Tilt+Neon&display=swap" rel="stylesheet"> 
</head>
<body>

    {% include 'nav.html' %}
    <div class="container">
        <h1 class="mt-5">Solicitação de adoção</h1>

        {% if sucesso %}
            <p class="alert alert-success">Obrigado por enviar sua solicitação de adoção.
                Entraremos em contato em breve para confirmar os detalhes.
                Enquanto isso, conheça nossos outros animais disponíveis para adoção e compartilhe com os amigos.
            </p>
        {% else %}

        <form class="mt-3" action="{% url 'adocao:solicitar_adocao' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="nome" class="form-label">Nome:</label>
                <input type="text" class="form-control" id="nome" name="nome" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">E-mail:</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="mb-3">
                <label for="endereco" class="form-label">Endereço:</label>
                <input type="endereco" class="form-control" id="endereco" name="endereco" required>
            </div>
            <div class="mb-3">
                <label for="outros_animais" class="form-label">Cuida de outros animais:</label>
                <input type="number" class="form-control" id="outros_animais" name="outros_animais" required>
            </div>
            <div class="mb-3">
                <label for="animal" class="form-label">Selecione o animal a ser adotado:</label>
                <select class="form-select" id="animal" name="animal" required>
                    {% for animal in animais_disponiveis %}
                        <option value="{{ animal.id }}">{{ animal.nome }}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
        
        {% endif %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

    {% if alerta_sucesso %}
    <script>
        window.onload = function() {
            alert('Solicitação de adoção enviada com sucesso! Em breve entraremos em contato com você!');
        }
    </script>
    {% endif %}

</body>
</html>
<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">

animal/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../static/css/footer.css">
    <title>Foter</title>
</head>
<body>
    <footer class="rodape">
        <div class="container-rodape">
            <a href="/admin">Administrativo</a>
            <a href="https://github.com/Renatarafaelaalves/ProjetoFinalSquadCarmenPortinho" target="_blank">Conheça o projeto</a>

        </div>
    </footer>
</body>
</html>

animal/templates/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="https://i.ibb.co/xFJLpqz/mi-au.jpg" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tilt+Neon&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/home.css">
    <title>Mi au amigo</title>
</head>
<body>
    {% include 'nav.html' %}
    <h1 class="titulo">Bem-vindo ao Abrigo Mi Au Amigo!</h1>
    <div class="texto">
        <p>Seja você um amante de gatos, cachorros ou de ambos, estamos felizes em recebê-lo ao nosso lar dedicado aos animais. No Abrigo Mi Au Amigo, acreditamos que cada patinha merece amor, cuidado e um lar para chamar de seu.</p>

        <p>Nossa missão é fornecer um ambiente seguro e acolhedor para animais que precisam de uma segunda chance. Com a ajuda de nossa incrível equipe e voluntários dedicados, trabalhamos para resgatar, reabilitar e encontrar lares amorosos para cada um de nossos amigos peludos.</p>

        <p>Ao navegar em nosso site, você terá a oportunidade de conhecer alguns dos animais adoráveis que estão atualmente à procura de um lar para sempre. Cada um deles tem uma história única e um coração cheio de amor para compartilhar.</p>

        <p>Além de encontrar seu novo companheiro de quatro patas, também incentivamos você a se envolver conosco de outras maneiras. Saiba mais sobre nossos programas de voluntariado e como você pode contribuir para tornar a vida de nossos animais ainda mais feliz.</p>

        <p>Juntos, podemos fazer a diferença na vida desses animais e espalhar mais amor e compaixão em nosso mundo. Obrigado por nos visitar e por considerar a adoção como a primeira opção. Estamos ansiosos para ajudá-lo a encontrar seu próximo melhor amigo!</p>

        <p>Com carinho,</p>
        <p>A Equipe do Abrigo Mi Au Amigo</p>
    </div>

    <div id="carouselExampleDark" class="carousel carousel-dark slide d-none d-md-block">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="10000">
            <img src="../static/media/pets1.jpg" class="imagem d-block w-100" alt="imagem de pets">
            <div class="carousel-caption d-none d-md-block">
              <h5 class="titulo">Conheça seu novo Mi Au Amigo</h5>
              <p>No Abrigo Mi Au Amigo, acreditamos que cada patinha merece amor, cuidado e um lar para chamar de seu.</p>
              <button class="buttons" type="button"><a href="/listar_animais">Ver mais</a></button>
            </div>
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <img src="../static/media/voluntarios.jpg" class="imagem d-block w-100" alt="imagem de pets">
            <div class="carousel-caption d-none d-md-block">
              <h5 class="titulo">Torne-se um voluntário</h5>
              <p>Junte-se a nós para fazer a diferença na vida de nossos amigos peludos!</p>
              <button class="buttons" type="button"><a href="{% url 'voluntarios:formulario_voluntario' %}">Ver mais</a></button>
            </div>
          </div>
          <div class="carousel-item">
            <img src="../static/media/pets2.jpg" class="imagem d-block w-100" alt="imagem de pets">
            <div class="carousel-caption d-none d-md-block">
              <h5 class="titulo">Adote um Mi Au Amigo agora</h5>
              <p>Nossa missão é fornecer um ambiente seguro e acolhedor para animais que precisam de uma segunda chance.</p>
              <button class="buttons" type="button"><a href="/adocao">Ver mais</a></button>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

    </div>
    {% include 'footer.html' %}
</body>
</html>

animal/templates/lista_animais.html
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/7699/7699744.png" type="image/x-icon">
    <title>Adote um bichinho</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Tilt+Neon&display=swap" rel="stylesheet">

    <style>
        .tabela  {
            font-family: "Tilt Neon", sans-serif;
            font-size: 25px;
            color: #333A73;
        }
        
        .link {
            text-decoration: none;
            color: #FBA834;
        }

    </style>
</head>
<body>
    {% include 'nav.html' %}
    <div class="container-fluid">
        <div class="row">
        <br>
          <hr>

            <div class="col-md">
                <div class="wrapper">
                    <div class="box width80">

                         <table class="tabela" cellpadding="20">
                            <tr>
                                <th>Foto</th>
                                <th>Nome</th>
                                <th>Raça</th>
                                <th>Status</th>
                                <th>Especie</th>
                            </tr>
                            {% for animal in animais%}
                                <tr class="tabela-linha">
                                    <td width="20%">
                                        <a class="link" href="{% url 'animais:ver_animal' animal.id %}"><img width="40%" src="{{animal.imagem.url}}"></a>
                                    </td>
                                    <td>
                                        <a class="link" href="{% url 'animais:ver_animal' animal.id %}">
                                        {{animal.nome}}</a>
                                    </td>
                                    <td>
                                        <a class="link" href="{% url 'animais:ver_animal' animal.id %}">
                                        {{animal.raca}}</a>
                                        
                                    </td>
                                    <td>
                                        {% if animal.adotado == False %}
                                            <a class="link" href="{% url 'animais:ver_animal' animal.id %}">
                                            <span class="badge text-bg-success">Para adoção</span></a>
                                        {% endif%}
                                    </td>
                                    <td>
                                        <a class="link" href="{% url 'animais:ver_animal' animal.id %}">
                                        {{animal.especie}}</a>
                                    </td>
                                </tr>
                            {% endfor %}                        
                            
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

animal/templates/nav.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navbar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/nav.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm">
            <div class="navbar_class">
                <a class="navbar-brand" href="/">
                    <img class="img_nav" src="https://cdn-icons-png.flaticon.com/512/1416/1416823.png" alt="">
                    Home
                </a>
                <a class="navbar-brand" href="/listar_animais">
                    <img class="img_nav" src="https://cdn-icons-png.flaticon.com/512/7699/7699744.png" alt="">
                    Animais
                </a>
                <a class="navbar-brand" href="/adocao">
                    <img class="img_nav" src="https://cdn-icons-png.flaticon.com/512/1312/1312640.png" alt="">
                    Adoção
                </a>
                <a class="navbar-brand" href="{% url 'voluntarios:formulario_voluntario' %}">
                    <img class="img_nav" src="https://cdn-icons-png.flaticon.com/512/6154/6154169.png" alt="">
                    Voluntários
                </a>
                <form class="d-flex ms-auto"  method="GET">
                    <input class="form-control me-2" type="search" name="especie" placeholder="Busque seu amigo" aria-label="Search">
                    <button class="btn btn-outline-success" id="btn_procurar" type="submit">Procurar</button>
                </form>              
            </div>
        </nav>
    </header>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>

animal/templates/ver_animal.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ animal.nome }}</title>
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/1834/1834619.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Tilt+Neon&display=swap" rel="stylesheet"> 
    
    <style>

    .font-vinho{
        font-family: "Tilt Neon", sans-serif;
        color: #333A73;
        text-align: center;
    }
    .span-bold {
        font-family: "Tilt Neon", sans-serif;
        color: #333A73;
        font-size: 20px;
    }

    p {
        font-family: "Tilt Neon", sans-serif;
        color: #FBA834;
        font-size: 18px;
    }

    .imagem {
        width: 100%;
        height: auto; 
        display: block;
        margin: 0 auto; 
    }

    </style>

</head>
<body>
    {% include 'nav.html' %}

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8 py-4">
                <h3 class="font-vinho">Informações do pet</h3>
                <div class="row mb-3">
                    <div class="col-md-3">
                        <span class="span-bold">Nome:</span>
                        <p>{{ animal.nome }}</p>
                    </div>
                    <div class="col-md-3">
                        <span class="span-bold">Idade:</span>
                        <p>{{ animal.idade }} {% if animal.idade == 1 %} ano {% else %} anos {% endif %}</p>
                    </div>
                    <div class="col-md-3">
                        <span class="span-bold">Sexo:</span>
                        <p>{{animal.sexo}}</p>
                    </div>
                </div> 
                <div class="row mb-3">
                    <div class="col-md-3"> 
                        <span class="span-bold">Especie:</span>
                        <p>{{animal.especie}}</p>   
                    </div>
                    <div class="col-md-3">
                        <span class="span-bold">Raça:</span>
                        <p>{{ animal.raca }}</p>
                    </div>
                </div>
                <div class="col-md-5"> 
                    <span class="span-bold">Imagem:</span>
                    <img src="{{ animal.imagem.url }}" alt="Imagem do Animal" class="imagem">
                </div>
                <hr>

                <div class="row">
                    <h3 class="font-vinho">Histórico de Saúde</h3>
                    <div class="col-md-3">
                        <span class="span-bold">Vacinas:</span>
                        <p>{{ animal.historico_saude.vacinas }}</p>
                    </div>
                    <div class="col-md-3">
                        <span class="span-bold">Castração:</span>
                        <p>{% if animal.historico_saude.castrado == 'C' %} Castrado {% else %} Não castrado {% endif %}</p>
                        <br>
                    </div>
                    <div class="col-md-2"> 
                        <span class="span-bold">Consultas:</span>
                        <p>{{ animal.historico_saude.idas_vet }}</p>
                    </div>
                    <a href="{% url 'adocao:solicitar_adocao' %}" class="btn btn-success btn-lg">SOLICITAR ADOÇÃO</a>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

voluntarios/templates/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Solicitação de voluntáriado</title>
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/6154/6154169.png" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Tilt+Neon&display=swap" rel="stylesheet">
</head>
<body>
    {% include 'nav.html' %}
    <div class="container">
        <h1 class="mt-5">Seja um Voluntário Mi Au Amigo</h1>
        <p>Junte-se a nós para fazer a diferença na vida de nossos amigos peludos! No "Mi au Amigo", acreditamos no poder transformador do amor e do cuidado pelos animais. Se você compartilha dessa paixão e deseja contribuir para o bem-estar dos nossos amiguinhos de quatro patas, temos várias maneiras pelas quais você pode se envolver como voluntário.</p>

        <form class="mt-3" action="{% url 'voluntarios:formulario_voluntario' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="nome" class="form-label">Nome:</label>
                <input type="text" class="form-control" id="nome" name="nome" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">E-mail:</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="mb-3">
                <label for="endereco" class="form-label">Endereço:</label>
                <input type="text" class="form-control" id="endereco" name="endereco" required>
            </div>
            <div class="mb-3">
                <label for="motivo" class="form-label">Me conta qual o motivo pelo qual você quer fazer parte da nossa equipe de voluntários:</label>
                <input type="text" class="form-control" id="motivo" name="motivo" required>
            </div>
            <div class="mb-3">
                <label for="disponibilidade" class="form-label">Disponibilidade:</label>
                <select class="form-select" id="disponibilidade" name="disponibilidade" required>
                    {% for opcao in opcoes_disponibilidade %}
                        <option value="{{ opcao.0 }}">{{ opcao.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="experiencia" class="form-label">Você tem experiência com os bichinhos:</label>
                <select class="form-select" id="experiencia" name="experiencia" required>
                    {% for opcao in opcoes_experiencia %}
                        <option value="{{ opcao.0 }}">{{ opcao.1 }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>

    {% if alerta_sucesso %}
    <script>
        window.onload = function() {
            alert('Cadastro realizado com sucesso!  Em breve entraremos em contato com você!');
        }
    </script>
    {% endif %}

</body>
</html>

<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">